name: Build 7.0 on debian stretch

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

env:
    TAG_VERSION: '7.0'

jobs:
    build-and-push-docker-image:
        name: "Build 7.0 on push to docker hub"
        uses: giuseppemorelli/docker-devbox-apache-php/build_and_push.yml@main

