name: 8.0 on debian

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build-and-push-docker-image:
        name: "Build 8.0 on push to docker hub"
        uses: giuseppemorelli/docker-devbox-apache-php/.github/workflows/build_and_push.yml@main
        with:
            tagversion: '8.0'
            folder: './php-8.0-debian'
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
