name: 7.4 on debian

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build-and-push-docker-image:
        name: "Build 7.4 on push to docker hub"
        uses: giuseppemorelli/docker-devbox-apache-php/.github/workflows/build_and_push.yml@main
        with:
            tagversion: '7.4'
            folder: './php-7.4-debian'
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
